name: publish

on:
  push:
    tags:
      - 'v1.*'
      - 'gh-action-test-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: get version
        run: echo version=$(awk -F"'" '{ print $2}' src/kubernetes_validate/version.py)  >> $GITHUB_OUTPUT
        id: version
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ steps.version.outputs.version}}
          context: "{{defaultContext}}"
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}}
          labels: org.opencontainers.image.source=https://github.com/${{github.repository}}

  pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/kubernetes-validate
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build pypi package
        run: |
          python -m pip install build twine && python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
