name: publish

on:
  push:
    tags:
      - 'v1.*'
      - 'gh-action-test-*'

jobs:
- name: Build and push Docker image
  uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
  with:
    context: .
    file: ./Dockerfile
    push: true
    tag: ghcr.io/${{github.repository}}:${{github.ref}}
